language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t raminblair/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true -t raminblair/react-test npm run test -- --coverage

after_success:
  - docker build -t raminblair/multi-client ./client
  - docker build -t raminblair/multi-nginx ./nginx
  - docker build -t raminblair/multi-server ./server
  - docker build -t raminblair/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push raminblair/multi-client
  - docker push raminblair/multi-nginx
  - docker push raminblair/multi-server
  - docker push raminblair/multi-worker